using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SprintFlowAPI.Models;

/// <summary>
/// Domain model representing a Project workspace in SprintFlow.
/// Uses numeric BIGINT identifier auto-generated by the database.
/// </summary>
public class Project
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    [Required]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    [Required]
    [MaxLength(1000)]
    public string Description { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }

    // Navigation properties

    /// <summary>
    /// Stories owned by this project.
    /// Cascade delete: removing a project removes all its stories.
    /// </summary>
    public ICollection<Story> Stories { get; set; } = new List<Story>();

    /// <summary>
    /// Team member associations for this project.
    /// Cascade delete: removing a project removes all membership records.
    /// </summary>
    public ICollection<ProjectMember> Members { get; set; } = new List<ProjectMember>();
}
